server:
  port: 9528
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://127.0.0.1:8848
    gateway:
      routes:
        - id: pay_route1
          uri: http://127.0.0.1:9001
          predicates:
            - Path=/pay/**