server:
  port: 9001
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: "http://127.0.0.1:8858"
        port: 8719
